//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package armcodesigning

// AccountClientCheckNameAvailabilityResponse contains the response from method AccountClient.CheckNameAvailability.
type AccountClientCheckNameAvailabilityResponse struct {
	CheckNameAvailabilityResult
}

// AccountClientCreateResponse contains the response from method AccountClient.BeginCreate.
type AccountClientCreateResponse struct {
	Account
}

// AccountClientDeleteResponse contains the response from method AccountClient.BeginDelete.
type AccountClientDeleteResponse struct {
	// placeholder for future response values
}

// AccountClientGetResponse contains the response from method AccountClient.Get.
type AccountClientGetResponse struct {
	Account
}

// AccountClientListByResourceGroupResponse contains the response from method AccountClient.NewListByResourceGroupPager.
type AccountClientListByResourceGroupResponse struct {
	Accounts
}

// AccountClientListBySubscriptionResponse contains the response from method AccountClient.NewListBySubscriptionPager.
type AccountClientListBySubscriptionResponse struct {
	Accounts
}

// AccountClientUpdateResponse contains the response from method AccountClient.Update.
type AccountClientUpdateResponse struct {
	Account
}

// CertificateProfileClientCreateResponse contains the response from method CertificateProfileClient.BeginCreate.
type CertificateProfileClientCreateResponse struct {
	CertificateProfile
}

// CertificateProfileClientDeleteResponse contains the response from method CertificateProfileClient.BeginDelete.
type CertificateProfileClientDeleteResponse struct {
	// placeholder for future response values
}

// CertificateProfileClientGetResponse contains the response from method CertificateProfileClient.Get.
type CertificateProfileClientGetResponse struct {
	CertificateProfile
}

// CertificateProfileClientListByCodeSigningAccountResponse contains the response from method CertificateProfileClient.NewListByCodeSigningAccountPager.
type CertificateProfileClientListByCodeSigningAccountResponse struct {
	CertificateProfiles
}

// CertificateProfileClientUpdateResponse contains the response from method CertificateProfileClient.Update.
type CertificateProfileClientUpdateResponse struct {
	CertificateProfile
}

// OperationsClientListResponse contains the response from method OperationsClient.NewListPager.
type OperationsClientListResponse struct {
	OperationListResult
}
