// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armavs_test

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/avs/armavs/v3"
	"log"
)

// Generated from example definition: 2024-09-01/WorkloadNetworks_CreateVMGroup.json
func ExampleWorkloadNetworkVMGroupsClient_BeginCreate() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armavs.NewClientFactory("00000000-0000-0000-0000-000000000000", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewWorkloadNetworkVMGroupsClient().BeginCreate(ctx, "group1", "cloud1", "vmGroup1", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	res, err := poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armavs.WorkloadNetworkVMGroupsClientCreateResponse{
	// 	WorkloadNetworkVMGroup: &armavs.WorkloadNetworkVMGroup{
	// 		ID: to.Ptr("/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.AVS/privateClouds/cloud1/workloadNetworks/default/vmGroups/vmGroup1"),
	// 		Name: to.Ptr("vmGroup1"),
	// 		Properties: &armavs.WorkloadNetworkVMGroupProperties{
	// 			DisplayName: to.Ptr("vmGroup1"),
	// 			Members: []*string{
	// 				to.Ptr("564d43da-fefc-2a3b-1d92-42855622fa50"),
	// 			},
	// 			Status: to.Ptr(armavs.VMGroupStatusEnumSUCCESS),
	// 			Revision: to.Ptr[int64](1),
	// 		},
	// 		Type: to.Ptr("Microsoft.AVS/privateClouds/workloadNetworks/vmGroups"),
	// 	},
	// }
}

// Generated from example definition: 2024-09-01/WorkloadNetworks_DeleteVMGroup.json
func ExampleWorkloadNetworkVMGroupsClient_BeginDelete() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armavs.NewClientFactory("00000000-0000-0000-0000-000000000000", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewWorkloadNetworkVMGroupsClient().BeginDelete(ctx, "group1", "vmGroup1", "cloud1", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	res, err := poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armavs.WorkloadNetworkVMGroupsClientDeleteResponse{
	// }
}

// Generated from example definition: 2024-09-01/WorkloadNetworks_GetVMGroup.json
func ExampleWorkloadNetworkVMGroupsClient_Get() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armavs.NewClientFactory("00000000-0000-0000-0000-000000000000", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewWorkloadNetworkVMGroupsClient().Get(ctx, "group1", "cloud1", "vmGroup1", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armavs.WorkloadNetworkVMGroupsClientGetResponse{
	// 	WorkloadNetworkVMGroup: &armavs.WorkloadNetworkVMGroup{
	// 		ID: to.Ptr("/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.AVS/privateClouds/cloud1/workloadNetworks/default/vmGroups/vmGroup1"),
	// 		Name: to.Ptr("cloud1"),
	// 		Properties: &armavs.WorkloadNetworkVMGroupProperties{
	// 			DisplayName: to.Ptr("vmGroup1"),
	// 			Members: []*string{
	// 				to.Ptr("564d43da-fefc-2a3b-1d92-42855622fa50"),
	// 			},
	// 			Status: to.Ptr(armavs.VMGroupStatusEnumSUCCESS),
	// 			Revision: to.Ptr[int64](1),
	// 		},
	// 		Type: to.Ptr("Microsoft.AVS/privateClouds/workloadNetworks/vmGroups"),
	// 	},
	// }
}

// Generated from example definition: 2024-09-01/WorkloadNetworks_ListVMGroups.json
func ExampleWorkloadNetworkVMGroupsClient_NewListPager() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armavs.NewClientFactory("00000000-0000-0000-0000-000000000000", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	pager := clientFactory.NewWorkloadNetworkVMGroupsClient().NewListPager("group1", "cloud1", nil)
	for pager.More() {
		page, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range page.Value {
			// You could use page here. We use blank identifier for just demo purposes.
			_ = v
		}
		// If the HTTP response code is 200 as defined in example definition, your page structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
		// page = armavs.WorkloadNetworkVMGroupsClientListResponse{
		// 	WorkloadNetworkVMGroupsList: armavs.WorkloadNetworkVMGroupsList{
		// 		Value: []*armavs.WorkloadNetworkVMGroup{
		// 			{
		// 				ID: to.Ptr("/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.AVS/privateClouds/cloud1/workloadNetworks/default/vmGroups/vmGroup1"),
		// 				Name: to.Ptr("cloud1"),
		// 				Properties: &armavs.WorkloadNetworkVMGroupProperties{
		// 					DisplayName: to.Ptr("vmGroup1"),
		// 					Members: []*string{
		// 						to.Ptr("564d43da-fefc-2a3b-1d92-42855622fa50"),
		// 					},
		// 					Status: to.Ptr(armavs.VMGroupStatusEnumSUCCESS),
		// 					Revision: to.Ptr[int64](1),
		// 				},
		// 				Type: to.Ptr("Microsoft.AVS/privateClouds/workloadNetworks/vmGroups"),
		// 			},
		// 		},
		// 	},
		// }
	}
}

// Generated from example definition: 2024-09-01/WorkloadNetworks_UpdateVMGroup.json
func ExampleWorkloadNetworkVMGroupsClient_BeginUpdate() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armavs.NewClientFactory("00000000-0000-0000-0000-000000000000", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewWorkloadNetworkVMGroupsClient().BeginUpdate(ctx, "group1", "cloud1", "vmGroup1", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	res, err := poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res = armavs.WorkloadNetworkVMGroupsClientUpdateResponse{
	// 	WorkloadNetworkVMGroup: &armavs.WorkloadNetworkVMGroup{
	// 		ID: to.Ptr("/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.AVS/privateClouds/cloud1/workloadNetworks/default/vmGroups/vmGroup1"),
	// 		Name: to.Ptr("cloud1"),
	// 		Properties: &armavs.WorkloadNetworkVMGroupProperties{
	// 			DisplayName: to.Ptr("vmGroup1"),
	// 			Members: []*string{
	// 				to.Ptr("564d43da-fefc-2a3b-1d92-42855622fa50"),
	// 			},
	// 			Status: to.Ptr(armavs.VMGroupStatusEnumSUCCESS),
	// 			Revision: to.Ptr[int64](2),
	// 		},
	// 		Type: to.Ptr("Microsoft.AVS/privateClouds/workloadNetworks/vmGroups"),
	// 	},
	// }
}
