# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
    - sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
    - sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/

stages:
- template: /eng/pipelines/templates/jobs/archetype-sdk-client.yml
  parameters:
    IncludeRelease: true
    ServiceDirectory: 'resourcemanager/programmableconnectivity/armprogrammableconnectivity'
