//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package armoperationalinsights

// WorkspacesClientGetNSPResponse contains the response from method WorkspacesClient.GetNSP.
type WorkspacesClientGetNSPResponse struct {
	// NSP Configuration.
	NetworkSecurityPerimeterConfiguration
}

// WorkspacesClientListNSPResponse contains the response from method WorkspacesClient.NewListNSPPager.
type WorkspacesClientListNSPResponse struct {
	// A list of NSP configurations.
	NetworkSecurityPerimeterConfigurationListResult
}

// WorkspacesClientReconcileNSPResponse contains the response from method WorkspacesClient.BeginReconcileNSP.
type WorkspacesClientReconcileNSPResponse struct {
	// placeholder for future response values
}
