//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/azurestack/armazurestack"
	"net/http"
	"net/url"
	"regexp"
)

// CustomerSubscriptionsServer is a fake server for instances of the armazurestack.CustomerSubscriptionsClient type.
type CustomerSubscriptionsServer struct {
	// Create is the fake for method CustomerSubscriptionsClient.Create
	// HTTP status codes to indicate success: http.StatusOK
	Create func(ctx context.Context, resourceGroup string, registrationName string, customerSubscriptionName string, customerCreationParameters armazurestack.CustomerSubscription, options *armazurestack.CustomerSubscriptionsClientCreateOptions) (resp azfake.Responder[armazurestack.CustomerSubscriptionsClientCreateResponse], errResp azfake.ErrorResponder)

	// Delete is the fake for method CustomerSubscriptionsClient.Delete
	// HTTP status codes to indicate success: http.StatusOK, http.StatusNoContent
	Delete func(ctx context.Context, resourceGroup string, registrationName string, customerSubscriptionName string, options *armazurestack.CustomerSubscriptionsClientDeleteOptions) (resp azfake.Responder[armazurestack.CustomerSubscriptionsClientDeleteResponse], errResp azfake.ErrorResponder)

	// Get is the fake for method CustomerSubscriptionsClient.Get
	// HTTP status codes to indicate success: http.StatusOK
	Get func(ctx context.Context, resourceGroup string, registrationName string, customerSubscriptionName string, options *armazurestack.CustomerSubscriptionsClientGetOptions) (resp azfake.Responder[armazurestack.CustomerSubscriptionsClientGetResponse], errResp azfake.ErrorResponder)

	// NewListPager is the fake for method CustomerSubscriptionsClient.NewListPager
	// HTTP status codes to indicate success: http.StatusOK
	NewListPager func(resourceGroup string, registrationName string, options *armazurestack.CustomerSubscriptionsClientListOptions) (resp azfake.PagerResponder[armazurestack.CustomerSubscriptionsClientListResponse])
}

// NewCustomerSubscriptionsServerTransport creates a new instance of CustomerSubscriptionsServerTransport with the provided implementation.
// The returned CustomerSubscriptionsServerTransport instance is connected to an instance of armazurestack.CustomerSubscriptionsClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewCustomerSubscriptionsServerTransport(srv *CustomerSubscriptionsServer) *CustomerSubscriptionsServerTransport {
	return &CustomerSubscriptionsServerTransport{
		srv:          srv,
		newListPager: newTracker[azfake.PagerResponder[armazurestack.CustomerSubscriptionsClientListResponse]](),
	}
}

// CustomerSubscriptionsServerTransport connects instances of armazurestack.CustomerSubscriptionsClient to instances of CustomerSubscriptionsServer.
// Don't use this type directly, use NewCustomerSubscriptionsServerTransport instead.
type CustomerSubscriptionsServerTransport struct {
	srv          *CustomerSubscriptionsServer
	newListPager *tracker[azfake.PagerResponder[armazurestack.CustomerSubscriptionsClientListResponse]]
}

// Do implements the policy.Transporter interface for CustomerSubscriptionsServerTransport.
func (c *CustomerSubscriptionsServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	var resp *http.Response
	var err error

	switch method {
	case "CustomerSubscriptionsClient.Create":
		resp, err = c.dispatchCreate(req)
	case "CustomerSubscriptionsClient.Delete":
		resp, err = c.dispatchDelete(req)
	case "CustomerSubscriptionsClient.Get":
		resp, err = c.dispatchGet(req)
	case "CustomerSubscriptionsClient.NewListPager":
		resp, err = c.dispatchNewListPager(req)
	default:
		err = fmt.Errorf("unhandled API %s", method)
	}

	if err != nil {
		return nil, err
	}

	return resp, nil
}

func (c *CustomerSubscriptionsServerTransport) dispatchCreate(req *http.Request) (*http.Response, error) {
	if c.srv.Create == nil {
		return nil, &nonRetriableError{errors.New("fake for method Create not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/resourceGroups/(?P<resourceGroup>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.AzureStack/registrations/(?P<registrationName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/customerSubscriptions/(?P<customerSubscriptionName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if matches == nil || len(matches) < 4 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	body, err := server.UnmarshalRequestAsJSON[armazurestack.CustomerSubscription](req)
	if err != nil {
		return nil, err
	}
	resourceGroupParam, err := url.PathUnescape(matches[regex.SubexpIndex("resourceGroup")])
	if err != nil {
		return nil, err
	}
	registrationNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("registrationName")])
	if err != nil {
		return nil, err
	}
	customerSubscriptionNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("customerSubscriptionName")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := c.srv.Create(req.Context(), resourceGroupParam, registrationNameParam, customerSubscriptionNameParam, body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).CustomerSubscription, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *CustomerSubscriptionsServerTransport) dispatchDelete(req *http.Request) (*http.Response, error) {
	if c.srv.Delete == nil {
		return nil, &nonRetriableError{errors.New("fake for method Delete not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/resourceGroups/(?P<resourceGroup>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.AzureStack/registrations/(?P<registrationName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/customerSubscriptions/(?P<customerSubscriptionName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if matches == nil || len(matches) < 4 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	resourceGroupParam, err := url.PathUnescape(matches[regex.SubexpIndex("resourceGroup")])
	if err != nil {
		return nil, err
	}
	registrationNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("registrationName")])
	if err != nil {
		return nil, err
	}
	customerSubscriptionNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("customerSubscriptionName")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := c.srv.Delete(req.Context(), resourceGroupParam, registrationNameParam, customerSubscriptionNameParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK, http.StatusNoContent}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK, http.StatusNoContent", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *CustomerSubscriptionsServerTransport) dispatchGet(req *http.Request) (*http.Response, error) {
	if c.srv.Get == nil {
		return nil, &nonRetriableError{errors.New("fake for method Get not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/resourceGroups/(?P<resourceGroup>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.AzureStack/registrations/(?P<registrationName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/customerSubscriptions/(?P<customerSubscriptionName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if matches == nil || len(matches) < 4 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	resourceGroupParam, err := url.PathUnescape(matches[regex.SubexpIndex("resourceGroup")])
	if err != nil {
		return nil, err
	}
	registrationNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("registrationName")])
	if err != nil {
		return nil, err
	}
	customerSubscriptionNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("customerSubscriptionName")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := c.srv.Get(req.Context(), resourceGroupParam, registrationNameParam, customerSubscriptionNameParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).CustomerSubscription, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *CustomerSubscriptionsServerTransport) dispatchNewListPager(req *http.Request) (*http.Response, error) {
	if c.srv.NewListPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewListPager not implemented")}
	}
	newListPager := c.newListPager.get(req)
	if newListPager == nil {
		const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/resourceGroups/(?P<resourceGroup>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.AzureStack/registrations/(?P<registrationName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/customerSubscriptions`
		regex := regexp.MustCompile(regexStr)
		matches := regex.FindStringSubmatch(req.URL.EscapedPath())
		if matches == nil || len(matches) < 3 {
			return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
		}
		resourceGroupParam, err := url.PathUnescape(matches[regex.SubexpIndex("resourceGroup")])
		if err != nil {
			return nil, err
		}
		registrationNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("registrationName")])
		if err != nil {
			return nil, err
		}
		resp := c.srv.NewListPager(resourceGroupParam, registrationNameParam, nil)
		newListPager = &resp
		c.newListPager.add(req, newListPager)
		server.PagerResponderInjectNextLinks(newListPager, req, func(page *armazurestack.CustomerSubscriptionsClientListResponse, createLink func() string) {
			page.NextLink = to.Ptr(createLink())
		})
	}
	resp, err := server.PagerResponderNext(newListPager, req)
	if err != nil {
		return nil, err
	}
	if !contains([]int{http.StatusOK}, resp.StatusCode) {
		c.newListPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newListPager) {
		c.newListPager.remove(req)
	}
	return resp, nil
}
