// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package armprofessionalservice

// OperationClientGetResponse contains the response from method OperationClient.BeginGet.
type OperationClientGetResponse struct {
	// ProfessionalService REST API resource definition.
	Resource
}

// OperationsClientListResponse contains the response from method OperationsClient.NewListPager.
type OperationsClientListResponse struct {
	// professionalService app operation response with continuation.
	AppOperationsResponseWithContinuation
}

// SubscriptionLevelClientCreateOrUpdateResponse contains the response from method SubscriptionLevelClient.BeginCreateOrUpdate.
type SubscriptionLevelClientCreateOrUpdateResponse struct {
	// ProfessionalService REST API resource definition.
	Resource
}

// SubscriptionLevelClientDeleteResponse contains the response from method SubscriptionLevelClient.BeginDelete.
type SubscriptionLevelClientDeleteResponse struct {
	// placeholder for future response values
}

// SubscriptionLevelClientGetResponse contains the response from method SubscriptionLevelClient.Get.
type SubscriptionLevelClientGetResponse struct {
	// ProfessionalService REST API resource definition.
	Resource
}

// SubscriptionLevelClientListByAzureSubscriptionResponse contains the response from method SubscriptionLevelClient.NewListByAzureSubscriptionPager.
type SubscriptionLevelClientListByAzureSubscriptionResponse struct {
	// professionalService resources response with continuation.
	ResourceResponseWithContinuation
}

// SubscriptionLevelClientListByResourceGroupResponse contains the response from method SubscriptionLevelClient.NewListByResourceGroupPager.
type SubscriptionLevelClientListByResourceGroupResponse struct {
	// professionalService resources response with continuation.
	ResourceResponseWithContinuation
}

// SubscriptionLevelClientUpdateToUnsubscribedResponse contains the response from method SubscriptionLevelClient.BeginUpdateToUnsubscribed.
type SubscriptionLevelClientUpdateToUnsubscribedResponse struct {
	// placeholder for future response values
}
