//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package armscan

// AzureScanningAccountClientCreateResponse contains the response from method AzureScanningAccountClient.Create.
type AzureScanningAccountClientCreateResponse struct {
	ScanningAccount
}

// AzureScanningAccountClientDeleteResponse contains the response from method AzureScanningAccountClient.Delete.
type AzureScanningAccountClientDeleteResponse struct {
	// placeholder for future response values
}

// AzureScanningAccountClientGetResponse contains the response from method AzureScanningAccountClient.Get.
type AzureScanningAccountClientGetResponse struct {
	ScanningAccount
}

// AzureScanningAccountClientListByResourceGroupResponse contains the response from method AzureScanningAccountClient.ListByResourceGroup.
type AzureScanningAccountClientListByResourceGroupResponse struct {
	ScanningAccounts
}

// AzureScanningAccountClientListBySubscriptionResponse contains the response from method AzureScanningAccountClient.ListBySubscription.
type AzureScanningAccountClientListBySubscriptionResponse struct {
	ScanningAccounts
}

// AzureScanningAccountClientUpdateResponse contains the response from method AzureScanningAccountClient.Update.
type AzureScanningAccountClientUpdateResponse struct {
	ScanningAccount
}

// OperationsClientListResponse contains the response from method OperationsClient.List.
type OperationsClientListResponse struct {
	OperationListResult
}
