// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armbotservice

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
)

// ClientFactory is a client factory used to create any client in this module.
// Don't use this type directly, use NewClientFactory instead.
type ClientFactory struct {
	subscriptionID string
	internal       *arm.Client
}

// NewClientFactory creates a new instance of ClientFactory with the specified values.
// The parameter values will be propagated to any client created from this factory.
//   - subscriptionID - The ID of the target subscription. The value must be an UUID.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - pass nil to accept the default values.
func NewClientFactory(subscriptionID string, credential azcore.TokenCredential, options *arm.ClientOptions) (*ClientFactory, error) {
	internal, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	return &ClientFactory{
		subscriptionID: subscriptionID,
		internal:       internal,
	}, nil
}

// NewBotChannelsClient creates a new instance of BotChannelsClient.
func (c *ClientFactory) NewBotChannelsClient() *BotChannelsClient {
	return &BotChannelsClient{
		subscriptionID: c.subscriptionID,
		internal:       c.internal,
	}
}

// NewBotConnectionOperationGroupClient creates a new instance of BotConnectionOperationGroupClient.
func (c *ClientFactory) NewBotConnectionOperationGroupClient() *BotConnectionOperationGroupClient {
	return &BotConnectionOperationGroupClient{
		subscriptionID: c.subscriptionID,
		internal:       c.internal,
	}
}

// NewBotsClient creates a new instance of BotsClient.
func (c *ClientFactory) NewBotsClient() *BotsClient {
	return &BotsClient{
		subscriptionID: c.subscriptionID,
		internal:       c.internal,
	}
}

// NewBotsOperationGroupClient creates a new instance of BotsOperationGroupClient.
func (c *ClientFactory) NewBotsOperationGroupClient() *BotsOperationGroupClient {
	return &BotsOperationGroupClient{
		internal: c.internal,
	}
}

// NewConnectionSettingsClient creates a new instance of ConnectionSettingsClient.
func (c *ClientFactory) NewConnectionSettingsClient() *ConnectionSettingsClient {
	return &ConnectionSettingsClient{
		subscriptionID: c.subscriptionID,
		internal:       c.internal,
	}
}

// NewHostSettingsOperationGroupClient creates a new instance of HostSettingsOperationGroupClient.
func (c *ClientFactory) NewHostSettingsOperationGroupClient() *HostSettingsOperationGroupClient {
	return &HostSettingsOperationGroupClient{
		subscriptionID: c.subscriptionID,
		internal:       c.internal,
	}
}

// NewNetworkSecurityPerimeterConfigurationsClient creates a new instance of NetworkSecurityPerimeterConfigurationsClient.
func (c *ClientFactory) NewNetworkSecurityPerimeterConfigurationsClient() *NetworkSecurityPerimeterConfigurationsClient {
	return &NetworkSecurityPerimeterConfigurationsClient{
		subscriptionID: c.subscriptionID,
		internal:       c.internal,
	}
}

// NewOperationResultsOperationGroupClient creates a new instance of OperationResultsOperationGroupClient.
func (c *ClientFactory) NewOperationResultsOperationGroupClient() *OperationResultsOperationGroupClient {
	return &OperationResultsOperationGroupClient{
		subscriptionID: c.subscriptionID,
		internal:       c.internal,
	}
}

// NewOperationsClient creates a new instance of OperationsClient.
func (c *ClientFactory) NewOperationsClient() *OperationsClient {
	return &OperationsClient{
		internal: c.internal,
	}
}

// NewPrivateEndpointConnectionsClient creates a new instance of PrivateEndpointConnectionsClient.
func (c *ClientFactory) NewPrivateEndpointConnectionsClient() *PrivateEndpointConnectionsClient {
	return &PrivateEndpointConnectionsClient{
		subscriptionID: c.subscriptionID,
		internal:       c.internal,
	}
}

// NewQnAMakerEndpointKeysOperationGroupClient creates a new instance of QnAMakerEndpointKeysOperationGroupClient.
func (c *ClientFactory) NewQnAMakerEndpointKeysOperationGroupClient() *QnAMakerEndpointKeysOperationGroupClient {
	return &QnAMakerEndpointKeysOperationGroupClient{
		subscriptionID: c.subscriptionID,
		internal:       c.internal,
	}
}
