// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package armazurestack

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
)

// ClientFactory is a client factory used to create any client in this module.
// Don't use this type directly, use NewClientFactory instead.
type ClientFactory struct {
	internal *arm.Client
}

// NewClientFactory creates a new instance of ClientFactory with the specified values.
// The parameter values will be propagated to any client created from this factory.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - pass nil to accept the default values.
func NewClientFactory(credential azcore.TokenCredential, options *arm.ClientOptions) (*ClientFactory, error) {
	internal, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	return &ClientFactory{
		internal: internal,
	}, nil
}

// NewCloudManifestFileClient creates a new instance of CloudManifestFileClient.
func (c *ClientFactory) NewCloudManifestFileClient() *CloudManifestFileClient {
	return &CloudManifestFileClient{
		internal: c.internal,
	}
}

// NewCustomerSubscriptionsClient creates a new instance of CustomerSubscriptionsClient.
func (c *ClientFactory) NewCustomerSubscriptionsClient(subscriptionID string) *CustomerSubscriptionsClient {
	return &CustomerSubscriptionsClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}

// NewDeploymentLicenseClient creates a new instance of DeploymentLicenseClient.
func (c *ClientFactory) NewDeploymentLicenseClient(subscriptionID string) *DeploymentLicenseClient {
	return &DeploymentLicenseClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}

// NewOperationsClient creates a new instance of OperationsClient.
func (c *ClientFactory) NewOperationsClient() *OperationsClient {
	return &OperationsClient{
		internal: c.internal,
	}
}

// NewProductsClient creates a new instance of ProductsClient.
func (c *ClientFactory) NewProductsClient(subscriptionID string) *ProductsClient {
	return &ProductsClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}

// NewRegistrationsClient creates a new instance of RegistrationsClient.
func (c *ClientFactory) NewRegistrationsClient(subscriptionID string) *RegistrationsClient {
	return &RegistrationsClient{
		subscriptionID: subscriptionID,
		internal:       c.internal,
	}
}
