//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/impact/armimpact"
	"net/http"
	"net/url"
	"regexp"
)

// WorkloadImpactsServer is a fake server for instances of the armimpact.WorkloadImpactsClient type.
type WorkloadImpactsServer struct {
	// BeginCreate is the fake for method WorkloadImpactsClient.BeginCreate
	// HTTP status codes to indicate success: http.StatusOK, http.StatusCreated
	BeginCreate func(ctx context.Context, workloadImpactName string, resource armimpact.WorkloadImpact, options *armimpact.WorkloadImpactsClientBeginCreateOptions) (resp azfake.PollerResponder[armimpact.WorkloadImpactsClientCreateResponse], errResp azfake.ErrorResponder)

	// Delete is the fake for method WorkloadImpactsClient.Delete
	// HTTP status codes to indicate success: http.StatusOK, http.StatusNoContent
	Delete func(ctx context.Context, workloadImpactName string, options *armimpact.WorkloadImpactsClientDeleteOptions) (resp azfake.Responder[armimpact.WorkloadImpactsClientDeleteResponse], errResp azfake.ErrorResponder)

	// Get is the fake for method WorkloadImpactsClient.Get
	// HTTP status codes to indicate success: http.StatusOK
	Get func(ctx context.Context, workloadImpactName string, options *armimpact.WorkloadImpactsClientGetOptions) (resp azfake.Responder[armimpact.WorkloadImpactsClientGetResponse], errResp azfake.ErrorResponder)

	// NewListBySubscriptionPager is the fake for method WorkloadImpactsClient.NewListBySubscriptionPager
	// HTTP status codes to indicate success: http.StatusOK
	NewListBySubscriptionPager func(options *armimpact.WorkloadImpactsClientListBySubscriptionOptions) (resp azfake.PagerResponder[armimpact.WorkloadImpactsClientListBySubscriptionResponse])
}

// NewWorkloadImpactsServerTransport creates a new instance of WorkloadImpactsServerTransport with the provided implementation.
// The returned WorkloadImpactsServerTransport instance is connected to an instance of armimpact.WorkloadImpactsClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewWorkloadImpactsServerTransport(srv *WorkloadImpactsServer) *WorkloadImpactsServerTransport {
	return &WorkloadImpactsServerTransport{
		srv:                        srv,
		beginCreate:                newTracker[azfake.PollerResponder[armimpact.WorkloadImpactsClientCreateResponse]](),
		newListBySubscriptionPager: newTracker[azfake.PagerResponder[armimpact.WorkloadImpactsClientListBySubscriptionResponse]](),
	}
}

// WorkloadImpactsServerTransport connects instances of armimpact.WorkloadImpactsClient to instances of WorkloadImpactsServer.
// Don't use this type directly, use NewWorkloadImpactsServerTransport instead.
type WorkloadImpactsServerTransport struct {
	srv                        *WorkloadImpactsServer
	beginCreate                *tracker[azfake.PollerResponder[armimpact.WorkloadImpactsClientCreateResponse]]
	newListBySubscriptionPager *tracker[azfake.PagerResponder[armimpact.WorkloadImpactsClientListBySubscriptionResponse]]
}

// Do implements the policy.Transporter interface for WorkloadImpactsServerTransport.
func (w *WorkloadImpactsServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	var resp *http.Response
	var err error

	switch method {
	case "WorkloadImpactsClient.BeginCreate":
		resp, err = w.dispatchBeginCreate(req)
	case "WorkloadImpactsClient.Delete":
		resp, err = w.dispatchDelete(req)
	case "WorkloadImpactsClient.Get":
		resp, err = w.dispatchGet(req)
	case "WorkloadImpactsClient.NewListBySubscriptionPager":
		resp, err = w.dispatchNewListBySubscriptionPager(req)
	default:
		err = fmt.Errorf("unhandled API %s", method)
	}

	if err != nil {
		return nil, err
	}

	return resp, nil
}

func (w *WorkloadImpactsServerTransport) dispatchBeginCreate(req *http.Request) (*http.Response, error) {
	if w.srv.BeginCreate == nil {
		return nil, &nonRetriableError{errors.New("fake for method BeginCreate not implemented")}
	}
	beginCreate := w.beginCreate.get(req)
	if beginCreate == nil {
		const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.Impact/workloadImpacts/(?P<workloadImpactName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
		regex := regexp.MustCompile(regexStr)
		matches := regex.FindStringSubmatch(req.URL.EscapedPath())
		if matches == nil || len(matches) < 2 {
			return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
		}
		body, err := server.UnmarshalRequestAsJSON[armimpact.WorkloadImpact](req)
		if err != nil {
			return nil, err
		}
		workloadImpactNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("workloadImpactName")])
		if err != nil {
			return nil, err
		}
		respr, errRespr := w.srv.BeginCreate(req.Context(), workloadImpactNameParam, body, nil)
		if respErr := server.GetError(errRespr, req); respErr != nil {
			return nil, respErr
		}
		beginCreate = &respr
		w.beginCreate.add(req, beginCreate)
	}

	resp, err := server.PollerResponderNext(beginCreate, req)
	if err != nil {
		return nil, err
	}

	if !contains([]int{http.StatusOK, http.StatusCreated}, resp.StatusCode) {
		w.beginCreate.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK, http.StatusCreated", resp.StatusCode)}
	}
	if !server.PollerResponderMore(beginCreate) {
		w.beginCreate.remove(req)
	}

	return resp, nil
}

func (w *WorkloadImpactsServerTransport) dispatchDelete(req *http.Request) (*http.Response, error) {
	if w.srv.Delete == nil {
		return nil, &nonRetriableError{errors.New("fake for method Delete not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.Impact/workloadImpacts/(?P<workloadImpactName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if matches == nil || len(matches) < 2 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	workloadImpactNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("workloadImpactName")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := w.srv.Delete(req.Context(), workloadImpactNameParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK, http.StatusNoContent}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK, http.StatusNoContent", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (w *WorkloadImpactsServerTransport) dispatchGet(req *http.Request) (*http.Response, error) {
	if w.srv.Get == nil {
		return nil, &nonRetriableError{errors.New("fake for method Get not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.Impact/workloadImpacts/(?P<workloadImpactName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if matches == nil || len(matches) < 2 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	workloadImpactNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("workloadImpactName")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := w.srv.Get(req.Context(), workloadImpactNameParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).WorkloadImpact, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (w *WorkloadImpactsServerTransport) dispatchNewListBySubscriptionPager(req *http.Request) (*http.Response, error) {
	if w.srv.NewListBySubscriptionPager == nil {
		return nil, &nonRetriableError{errors.New("fake for method NewListBySubscriptionPager not implemented")}
	}
	newListBySubscriptionPager := w.newListBySubscriptionPager.get(req)
	if newListBySubscriptionPager == nil {
		const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.Impact/workloadImpacts`
		regex := regexp.MustCompile(regexStr)
		matches := regex.FindStringSubmatch(req.URL.EscapedPath())
		if matches == nil || len(matches) < 1 {
			return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
		}
		resp := w.srv.NewListBySubscriptionPager(nil)
		newListBySubscriptionPager = &resp
		w.newListBySubscriptionPager.add(req, newListBySubscriptionPager)
		server.PagerResponderInjectNextLinks(newListBySubscriptionPager, req, func(page *armimpact.WorkloadImpactsClientListBySubscriptionResponse, createLink func() string) {
			page.NextLink = to.Ptr(createLink())
		})
	}
	resp, err := server.PagerResponderNext(newListBySubscriptionPager, req)
	if err != nil {
		return nil, err
	}
	if !contains([]int{http.StatusOK}, resp.StatusCode) {
		w.newListBySubscriptionPager.remove(req)
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", resp.StatusCode)}
	}
	if !server.PagerResponderMore(newListBySubscriptionPager) {
		w.newListBySubscriptionPager.remove(req)
	}
	return resp, nil
}
